version: '3'

services:
  php:
    build: ./src
    
    volumes:
      - './src:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      
  
  mysql:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: '1234'
      PMA_HOST: mysql
      PMA_USER: 'root'
      PMA_PASSWORD: '1234'
    depends_on:
        - mysql